### ISSUE TITLE
Crash when force-closing freezed Nautilus

### ISSUE THREAD

**Issue by rugk** [flatpak/xdg-desktop-portal-gtk#340]
I killed Nautilus due to a freeze and was told this in the bug report:
> It looks like something unrelated to nautilus. From your report, nautilus doesn't actually crash, you just force-close it, which leaves no crash information behind.
>
> But please report this crash in https://github.com/flatpak/xdg-desktop-portal-gtk/issues

See https://gitlab.gnome.org/GNOME/nautilus/-/issues/1766#note_1052276

So I'm doing this, even though I'm not entirely sure what has crashed this. I just clicked "Force close" (or similar) in GNOME.

```
$ coredumpctl gdb
           PID: 167475 (xdg-desktop-por)
           UID: 1000 (rugk)
           GID: 1000 (rugk)
        Signal: 11 (SEGV)
     Timestamp: Sat 2021-03-06 16:11:50 CET (1 day 2h ago)
  Command Line: /usr/libexec/xdg-desktop-portal-gtk
    Executable: /usr/libexec/xdg-desktop-portal-gtk
 Control Group: /user.slice/user-1000.slice/user@1000.service/xdg-desktop-portal-gtk.service
          Unit: user@1000.service
     User Unit: xdg-desktop-portal-gtk.service
         Slice: user-1000.slice
     Owner UID: 1000 (rugk)
       Boot ID: a7a8643c16234b0581ca811eb63bc399
    Machine ID: 8608a492bd3042f2aa60745b6f0ad895
      Hostname: FedRocks
       Storage: /var/lib/systemd/coredump/core.xdg-desktop-por.1000.a7a8643c16234b0581ca811eb63bc399.167475.1615043510000000.zst
       Message: Process 167475 (xdg-desktop-por) of user 1000 dumped core.
                
                Stack trace of thread 167475:
                #0  0x0000000000000000 n/a (n/a + 0x0)

GNU gdb (GDB) Fedora 10.1-2.fc33
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/libexec/xdg-desktop-portal-gtk...
Reading symbols from /usr/lib/debug/usr/libexec/xdg-desktop-portal-gtk-1.8.0-1.fc33.x86_64.debug...

warning: Can't open file /home/rugk/.config/dconf/user (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/dconf/user (deleted) during file-backed mapping note processing

warning: core file may not match specified executable file.
[New LWP 167475]
[New LWP 167476]
[New LWP 167479]
[New LWP 167478]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libwayland-egl.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/cb/d1930f8c301540f565bbb2761aa45547ede38b.debug
Missing separate debuginfo for /lib64/libblkid.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/fc/330f31b5843c8099e437ce5614c83ad6183e56.debug
Core was generated by `/usr/libexec/xdg-desktop-portal-gtk'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7fc3bcad9f40 (LWP 167475))]
Missing separate debuginfos, use: dnf debuginfo-install libvorbis-1.3.7-2.fc33.x86_64 libxcb-1.13.1-5.fc33.x86_64 libzstd-1.4.7-1.fc33.x86_64
(gdb) bt full
#0  0x0000000000000000 in  ()
#1  0x00007fc3bdd9111f in g_hash_table_lookup_node
    (hash_return=<synthetic pointer>, key=0x97, hash_table=0x5597ededd8b0<error reading variable: Cannot access memory at address 0x100000000>) at ../glib/ghash.c:473
        node_hash = <optimized out>
        hash_value = <optimized out>
        have_tombstone = 0
        step = 0
        node_index = <optimized out>
        first_tombstone = 0
        node_hash = <optimized out>
        __func__ = "g_hash_table_lookup"
#2  g_hash_table_lookup
    (hash_table=0x5597ededd8b0<error reading variable: Cannot access memory at address 0x100000000>, key=key@entry=0x97) at ../glib/ghash.c:1513
        node_hash = <optimized out>
        __func__ = "g_hash_table_lookup"
#3  0x00007fc3be2729d8 in lookup_cached_xatom (atom=0x97, display=0x5597edeae0e0)
    at x11/gdkproperty-x11.c:76
        display_x11 = 0x5597edeae0e0
        xatom = 0
        __func__ = "gdk_x11_atom_to_xatom_for_display"
#4  lookup_cached_xatom (atom=0x97, display=0x5597edeae0e0) at x11/gdkproperty-x11.c:67
        display_x11 = 0x5597edeae0e0
        xatom = 0
        __func__ = "gdk_x11_atom_to_xatom_for_display"
#5  gdk_x11_atom_to_xatom_for_display (display=0x5597edeae0e0, atom=0x97)
    at x11/gdkproperty-x11.c:109
        xatom = 0
        __func__ = "gdk_x11_atom_to_xatom_for_display"
#6  0x00007fc3be260b3e in handle_property_change
--Type <RET> for more, q to quit, c to continue without paging--
    (ev=0x7fc3a4002a00, device_manager=<optimized out>) at x11/gdkdevicemanager-xi2.c:1108
        device = 0x5597ee158000
        device = <optimized out>
        return_val = <optimized out>
        window = 0x0
        impl = <optimized out>
        source_device = <optimized out>
        scale = <optimized out>
        ev = 0x7fc3a4002a00
        __func__ = "gdk_x11_device_manager_xi2_translate_event"
#7  gdk_x11_device_manager_xi2_translate_event
    (xevent=0x7ffc7596ce30, event=0x5597ededce80, display=0x5597edeb5450, translator=<optimized out>) at x11/gdkdevicemanager-xi2.c:1538
        device = <optimized out>
        return_val = <optimized out>
        window = 0x0
        impl = <optimized out>
        source_device = <optimized out>
        scale = <optimized out>
        ev = 0x7fc3a4002a00
        __func__ = "gdk_x11_device_manager_xi2_translate_event"
#8  gdk_x11_device_manager_xi2_translate_event
    (translator=<optimized out>, display=0x5597edeb5450, event=0x5597ededce80, xevent=0x7ffc7596ce30) at x11/gdkdevicemanager-xi2.c:1478
        __func__ = "gdk_x11_device_manager_xi2_translate_event"
#9  0x00007fc3be2686e1 in _gdk_x11_event_translator_translate
    (translator=0x5597ee0a74f0, display=0x5597edeb5450, xevent=xevent@entry=0x7ffc7596ce30) at x11/gdkeventtranslator.c:51
        iface = 0x5597ee22f0d0
        event = 0x5597ededce80
        __func__ = "_gdk_x11_event_translator_translate"
--Type <RET> for more, q to quit, c to continue without paging--
#10 0x00007fc3be26c2b3 in gdk_event_source_translate_event
    (xevent=0x7ffc7596ce30, event_source=0x5597ee22ee60) at x11/gdkeventsource.c:243
        translator = <optimized out>
        list = 0x0
        filter_window = <optimized out>
        dpy = 0x5597ee0a8c00
        event = 0x0
        result = <optimized out>
        event_translator = <optimized out>
        event = <optimized out>

        xevent = 
            {type = 35, xany = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683}, xkey = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, state = 0, keycode = 0, same_screen = 0}, xbutton = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, state = 0, button = 0, same_screen = 0}, xmotion = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, state = 0, is_hint = 0 '\000', same_screen = 0}, xcrossing = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, mode = 0, detail = 0, same_screen = 0, focus = 0, state = 3991915456}, xfocus = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, mode = 1, detail = 0}, xexpose = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, x = 1, y = 0, width = -1543493120, height = 32707, count = 17007611}, xgraphicsexpose = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, drawable = 51539607683, x = 1, y = 0, width = -1543493120, height = 32707, count = 17007611, major_code = 0, minor_code = 411}, xnoexpose = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, drawable = 51539607683, major_code = 1, minor_code = 0}, xvisibility = {type = 35, serial = 165, send_--Type <RET> for more, q to quit, c to continue without paging--
event = 0, display = 0x5597ee0a8c00, window = 51539607683, state = 1}, xcreatewindow = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1, x = -1543493120, y = 32707, width = 17007611, height = 0, border_width = 411, override_redirect = 0}, xdestroywindow = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1}, xunmap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, from_configure = -1543493120}, xmap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, override_redirect = -1543493120}, xmaprequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1}, xreparent = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, parent = 140478246824448, x = 17007611, y = 0, override_redirect = 411}, xconfigure = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, x = -1543493120, y = 32707, width = 17007611, height = 0, border_width = 411, above = 6292650, override_redirect = 0}, xgravity = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, x = -1543493120, y = 32707}, xresizerequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, width = 1, height = 0}, xconfigurerequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1, x = -1543493120, y = 32707, width = 17007611, height = 0, border_width = 411, above = 6292650, detail = 0, value_mask = 0}, xcirculate = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, place = -1543493120}, xcirculaterequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1, place = -1543493120}, xproperty = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, atom = 1, time = 140478246824448, state = 17007611}, xselectionclear = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, selection = 1, time = 140478246824448}, xselectionrequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, owner = 51539607683, requestor = 1, selection = 140478246824448, target = 17007611, property = 411, time = 6292650}, xselection = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, requestor = 51539607683, selection = 1, target = 140478246824448, property = 17007611, time = 411}, xcolormap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, col--Type <RET> for more, q to quit, c to continue without paging--
ormap = 1, new = -1543493120, state = 32707}, xclient = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, message_type = 1, format = -1543493120, data = {b = "\373\203\003\001\000\000\000\000\233\001\000\000\000\000\000\000\252\004`", s = {-31749, 259, 0, 0, 411, 0, 0, 0, 1194, 96}, l = {17007611, 411, 6292650, 0, 0}}}, xmapping = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, request = 1, first_keycode = 0, count = -1543493120}, xerror = {type = 35, display = 0xa5, resourceid = 0, serial = 94111022091264, error_code = 131 '\203', request_code = 0 '\000', minor_code = 0 '\000'}, xkeymap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, key_vector = "\001\000\000\000\000\000\000\000\000*\000\244\303\177\000\000\373\203\003\001\000\000\000\000\233\001\000\000\000\000\000"}, xgeneric = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, extension = 131, evtype = 12}, xcookie = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, extension = 131, evtype = 12, cookie = 1, data = 0x7fc3a4002a00}, pad = {35, 165, 0, 94111022091264, 51539607683, 1, 140478246824448, 17007611, 411, 6292650, 0, 0, 94111020338112, 94111023480112, 94111023412800, 94111020345856, 94111023683792, 94111023314160, 94111023414544, 94111020450352, 94111023458096, 94111023411920, 94111020391904, 94111023488976}}
        xdisplay = 0x5597ee0a8c00
        event_source = 0x5597ee22ee60
        display_x11 = 0x5597edeb5450
#11 _gdk_x11_display_queue_events (display=0x5597edeb5450) at x11/gdkeventsource.c:341
        event = <optimized out>



        xevent = 
            {type = 35, xany = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683}, xkey = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, state = 0, keycode = 0, same_screen = 0}, xbutton = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, state = 0, button = 0, same_screen = 0}, xmotion = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, state = 0, --Type <RET> for more, q to quit, c to continue without paging--
is_hint = 0 '\000', same_screen = 0}, xcrossing = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, root = 1, subwindow = 140478246824448, time = 17007611, x = 411, y = 0, x_root = 6292650, y_root = 0, mode = 0, detail = 0, same_screen = 0, focus = 0, state = 3991915456}, xfocus = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, mode = 1, detail = 0}, xexpose = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, x = 1, y = 0, width = -1543493120, height = 32707, count = 17007611}, xgraphicsexpose = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, drawable = 51539607683, x = 1, y = 0, width = -1543493120, height = 32707, count = 17007611, major_code = 0, minor_code = 411}, xnoexpose = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, drawable = 51539607683, major_code = 1, minor_code = 0}, xvisibility = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, state = 1}, xcreatewindow = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1, x = -1543493120, y = 32707, width = 17007611, height = 0, border_width = 411, override_redirect = 0}, xdestroywindow = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1}, xunmap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, from_configure = -1543493120}, xmap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, override_redirect = -1543493120}, xmaprequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1}, xreparent = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, parent = 140478246824448, x = 17007611, y = 0, override_redirect = 411}, xconfigure = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, x = -1543493120, y = 32707, width = 17007611, height = 0, border_width = 411, above = 6292650, override_redirect = 0}, xgravity = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, event = 51539607683, window = 1, x = -1543493120, y = 32707}, xresizerequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, width = 1, height = 0}, xconfigurerequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1, x = -1543493120, y = 32707, width = 17007611, height = 0, border_width = 411, above = 6292650, detail = 0, value_mask = 0}, xcirculate = {type = 35, serial = 165, send_event = 0, display = 0x5597ee--Type <RET> for more, q to quit, c to continue without paging--
0a8c00, event = 51539607683, window = 1, place = -1543493120}, xcirculaterequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, parent = 51539607683, window = 1, place = -1543493120}, xproperty = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, atom = 1, time = 140478246824448, state = 17007611}, xselectionclear = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, selection = 1, time = 140478246824448}, xselectionrequest = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, owner = 51539607683, requestor = 1, selection = 140478246824448, target = 17007611, property = 411, time = 6292650}, xselection = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, requestor = 51539607683, selection = 1, target = 140478246824448, property = 17007611, time = 411}, xcolormap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, colormap = 1, new = -1543493120, state = 32707}, xclient = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, message_type = 1, format = -1543493120, data = {b = "\373\203\003\001\000\000\000\000\233\001\000\000\000\000\000\000\252\004`", s = {-31749, 259, 0, 0, 411, 0, 0, 0, 1194, 96}, l = {17007611, 411, 6292650, 0, 0}}}, xmapping = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, request = 1, first_keycode = 0, count = -1543493120}, xerror = {type = 35, display = 0xa5, resourceid = 0, serial = 94111022091264, error_code = 131 '\203', request_code = 0 '\000', minor_code = 0 '\000'}, xkeymap = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, window = 51539607683, key_vector = "\001\000\000\000\000\000\000\000\000*\000\244\303\177\000\000\373\203\003\001\000\000\000\000\233\001\000\000\000\000\000"}, xgeneric = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, extension = 131, evtype = 12}, xcookie = {type = 35, serial = 165, send_event = 0, display = 0x5597ee0a8c00, extension = 131, evtype = 12, cookie = 1, data = 0x7fc3a4002a00}, pad = {35, 165, 0, 94111022091264, 51539607683, 1, 140478246824448, 17007611, 411, 6292650, 0, 0, 94111020338112, 94111023480112, 94111023412800, 94111020345856, 94111023683792, 94111023314160, 94111023414544, 94111020450352, 94111023458096, 94111023411920, 94111020391904, 94111023488976}}

        xdisplay = 0x5597ee0a8c00
        event_source = 0x5597ee22ee60
        display_x11 = 0x5597edeb5450
#12 0x00007fc3be23485b in gdk_display_get_event (display=0x5597edeb5450)
--Type <RET> for more, q to quit, c to continue without paging--
    at gdkdisplay.c:442
        __func__ = "gdk_display_get_event"
#13 0x00007fc3be26c496 in gdk_event_source_dispatch
    (source=source@entry=0x5597ee22ee60, callback=<optimized out>, user_data=<optimized out>) at x11/gdkeventsource.c:363
        display = 0x5597edeb5450
        event = <optimized out>
#14 0x00007fc3bddaca9f in g_main_dispatch (context=0x5597edec2000) at ../glib/gmain.c:3325
        dispatch = <optimized out>
        prev_source = 0x0
        begin_time_nsec = 0
        was_in_call = <optimized out>
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x5597ee22ee60
        current = 0x5597edec3120
        i = 0
#15 g_main_context_dispatch (context=0x5597edec2000) at ../glib/gmain.c:4043
#16 0x00007fc3bddfea98 in g_main_context_iterate.constprop.0
    (context=0x5597edec2000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4119
        max_priority = 2147483647
        timeout = -1
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x5597edf20720
#17 0x00007fc3bddac163 in g_main_loop_run (loop=0x5597edf842a0) at ../glib/gmain.c:4317
--Type <RET> for more, q to quit, c to continue without paging--
        __func__ = "g_main_loop_run"
#18 0x00005597ed4a3962 in main (argc=<optimized out>, argv=<optimized out>)
    at src/xdg-desktop-portal-gtk.c:289
        owner_id = 1
        error = 0x0
        session_bus = <optimized out>

        context = 0x5597ee028d30
```

## system

Fedora 33 Workstation

```
$ dnf info xdg-desktop-portal-gtk
[…]
Installierte Pakete
Name         : xdg-desktop-portal-gtk
Version      : 1.8.0
Release      : 1.fc33
Architecture : x86_64
Size         : 631 k
Quelle       : xdg-desktop-portal-gtk-1.8.0-1.fc33.src.rpm
Repository   : @System
Aus Paketque : fedora
Summary      : Backend implementation for xdg-desktop-portal using GTK+
URL          : https://github.com/flatpak/xdg-desktop-portal-gtk
Lizenz       : LGPLv2+
Description  : A backend implementation for xdg-desktop-portal that is using
             : GTK+ and various pieces of GNOME infrastructure, such as the
             : org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus
             : interfaces.
```

**Comment by brenoperucchi** [comment]
Root cause for this one, from a fresh occurrence with a symbolized core. Short version: it is a GTK3 bug, not a portal bug, and it has been fixed upstream — just not released yet.

`xdg-desktop-portal-gtk` opens a second, X11 `GdkDisplay` (`ExternalWindowX11`, so it can reparent its dialogs onto XWayland clients) while `gdk_display_get_default()` stays the Wayland display. GDK's XI2 device-manager handler then does, in GTK 3.24.52:

```c
/* gdk/x11/gdkdevicemanager-xi2.c:1109 */
ev->property == gdk_x11_get_xatom_by_name ("Wacom Serial IDs")
```

and `gdk_x11_get_xatom_by_name()` is hardcoded to `gdk_display_get_default()` — the Wayland one. `gdk_x11_atom_to_xatom_for_display()` only asserts `GDK_IS_DISPLAY`, which a Wayland display satisfies, so it passes; `lookup_cached_xatom()` then does an unchecked `GDK_X11_DISPLAY (display)` cast, reads `atom_from_virtual` at the X11 struct offset out of a `GdkWaylandDisplay`, and hands the resulting garbage pointer to `g_hash_table_lookup()`, whose `hash_func` is NULL there. The process jumps to address 0.

Stack, symbolized via debuginfod (Arch Linux, GTK 3.24.52, GLib 2.88.3, xdg-desktop-portal-gtk 1.15.3, Xwayland 24.1.13, Hyprland 0.56.2):

```
#0  0x0000000000000000
#1  g_hash_table_lookup_node (hash_table=0x562ef005fef0, key=0xa7)  at ghash.c:430
#2  g_hash_table_lookup                                             at ghash.c:1496
#3  lookup_cached_xatom (display=0x562ef0047dd0, atom=0xa7)         at gdkproperty-x11.c:76
#4  lookup_cached_xatom                                             at gdkproperty-x11.c:67
#5  gdk_x11_atom_to_xatom_for_display                               at gdkproperty-x11.c:109
#6  handle_property_change                                          at gdkdevicemanager-xi2.c:1109
#7  gdk_x11_device_manager_xi2_translate_event                      at gdkdevicemanager-xi2.c:1559
#9  _gdk_x11_event_translator_translate                             at gdkeventtranslator.c:51
#11 _gdk_x11_display_queue_events                                   at gdkeventsource.c:341
#18 main                                                            at xdg-desktop-portal-gtk.c:290
```

Kernel side: `segfault at 0 ip 0000000000000000 sp 00007ffd05640d48 error 14` — error 14 is an instruction fetch on a non-present page, i.e. a call through a NULL function pointer, not a bad data read.

I confirmed the two displays directly in the core rather than inferring them: the object at `0x562ef0047dd0`, the one reaching frame #5, has a class vtable full of `gdk_wayland_display_dispose` / `_finalize` / `_get_name`, while the display the event came from, `0x562ef0167910`, has `gdk_x11_display_*`.

Fixed on `gtk-3-24` by c3b824a8f435, "x11: Fix wrong display when getting xatom" (GNOME/gtk!10105, a backport of 920259c25070):

```diff
-      ev->property == gdk_x11_get_xatom_by_name ("Wacom Serial IDs"))
+      ev->property == gdk_x11_get_xatom_by_name_for_display (gdk_device_get_display (device), "Wacom Serial IDs"))
```

That commit is dated 2026-06-30 and is not in any release: the latest `gtk-3-24` tag is 3.24.52 from 2026-03-23, and the fix sits 35 commits past it. So this will keep happening on current distro packages until a 3.24.53 ships, and there is nothing to fix on the portal side.

Worth noting about the trigger, since the code mentions Wacom: no tablet is required, and neither is any user interaction. The event here was `XIPropertyEvent{ deviceid = 7, property = 120, what = XIPropertyModified }`, and atom 120 on that Xwayland resolves to `"Device Enabled"` — GTK3 evaluates that atom comparison for *every* XI2 property change, and it is the comparison itself that faults, before anything looks at which property it was. Our portal had been idle for nine hours with no dialog open. It has crashed twice this way, with byte-identical stacks, on 2026-08-27 and 2026-09-10.

A sibling instance of the same defect, reached through `GtkMountOperation` instead of the XI2 handler, is GNOME/gtk#7749 — still open, and not fixed by the commit above.

**Comment by m10ust** [comment]
### Confirmed occurrence on GTK 3.24.52; possible KVM-switch trigger

Adding a symbolized occurrence of the same XI2 crash, with additional object-layout evidence and a possible hardware trigger.

On 2026-09-17 at 22:34:08 EDT, `/usr/lib/xdg-desktop-portal-gtk` (PID 2611) terminated with SIGSEGV while processing an XI2 device-property event. The owner suspects switching their KVM at the time. **The KVM connection is a hypothesis, not a confirmed reproduction:** no controlled switch/retest has been performed, and the core does not identify the physical device.

Expected behavior: input-device property changes should not terminate the portal service.

Environment at diagnosis:

```text
Arch Linux / Omarchy, Hyprland Wayland session, x86_64
xdg-desktop-portal-gtk 1.15.3-1
xdg-desktop-portal     1.22.1-2
gtk3                   1:3.24.52-1
glib2                  2.88.3-1
hyprland               0.56.2-3
xorg-xwayland          24.1.13-1
```

The crash frames were resolved with matching Arch debuginfod symbols. Selected frames (intermediate/inlined duplicates omitted):

```text
#0  0x0000000000000000
#1  g_hash_table_lookup_node(hash_table=0x56328c2b9500, key=0xa5)
      glib/ghash.c:430
#2  g_hash_table_lookup
      glib/ghash.c:1496
#3  lookup_cached_xatom(display=0x56328c298dc0, atom=0xa5)
      gdk/x11/gdkproperty-x11.c:76
#5  gdk_x11_atom_to_xatom_for_display(display=0x56328c298dc0, atom=0xa5)
      gdk/x11/gdkproperty-x11.c:109
#6  handle_property_change
      gdk/x11/gdkdevicemanager-xi2.c:1109
#7  gdk_x11_device_manager_xi2_translate_event(display=0x56328c331930, ...)
      gdk/x11/gdkdevicemanager-xi2.c:1559
#9  _gdk_x11_event_translator_translate
#11 _gdk_x11_display_queue_events
#12 gdk_display_get_event
#18 main
      src/xdg-desktop-portal-gtk.c:290
```

Runtime GType names read from the core confirm that `0x56328c298dc0`, passed to the X11 atom lookup, is a **GdkWaylandDisplay**, while `0x56328c331930`, receiving the event, is a **GdkX11Display**.

More specifically, the purported hash-table pointer `0x56328c2b9500` is exactly the Wayland display's **`subcompositor` pointer**. Interpreting that object as `GHashTable` produces `hash_func = 0x0`. Thus the immediate failure is an invalid interpretation of the Wayland object's layout, leading to a null indirect call, rather than evidence of a damaged real hash table.

The event in this core was:

```text
XIPropertyEvent: type=35, extension=131, evtype=12,
                 deviceid=6, property=120, what=2
```

The property name and physical device were not resolved for this occurrence. The crash occurs while evaluating the `"Wacom Serial IDs"` comparison; that string does not establish that a Wacom device was involved.

This confirms the mechanism described above and matches GTK commit [c3b824a8f435](https://github.com/GNOME/gtk/commit/c3b824a8f435dc975b2bee21a81254e3bb5a2229) / [GNOME/gtk!10105](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/10105), which replaces the default-display lookup with `gdk_x11_get_xatom_by_name_for_display(gdk_device_get_display(device), ...)`. The installed binary's matching source still contains the old call. A small clarification to the earlier comment: that commit also changes three display-dependent atom lookups in `gtk/gtkmountoperation-x11.c`; this does not establish that every manifestation of GTK issue #7749 is fixed.

No OOM kill was logged in the crash window. The service had run for approximately 2 days 3 hours, with a 68 MB memory peak. This is the only retained core for this portal on this machine. The journal records the service starting again at 22:46:11 EDT. No controlled reproduction or patched-build validation has been performed.

Only selected diagnostic details are included here; no raw core, credentials, or unrelated journal contents are attached.

Filed by GPT-6 via Codex, at the user's request.

**Comment by rugk** [comment]
>just not released yet.

Uhm, note my bug report is from 2021 with Fedora 33. We are far away from that, so I guess it should have been released for now.

**Comment by m10ust** [comment]
I guess GPT 6 does good on benchmarks but poorly on dates then. :P

**Comment by brenoperucchi** [comment]
Third occurrence here, plus a note on the close.

**New occurrence.** 2026-09-20 10:26:58 -03, `xdg-desktop-portal-gtk` PID 10193, same machine, same frames and same source lines as the stack above (addresses differ, ASLR). The event was again `XIPropertyEvent{ deviceid = 7, property = 120, what = XIPropertyModified }` — identical device and property to the previous one. The service had been up 21h15m with no dialog open. No OOM kill was logged in the crash window.

This time I read the runtime GType names straight out of the core, which pins the type confusion without relying on vtable contents:

```
0x5a2e6dc61a30  (receives the event)        -> GdkX11Display
0x5a2e6db5cdd0  (used for the atom lookup)  -> GdkWaylandDisplay
```

and the two `atom_from_virtual` tables side by side:

```
via GdkX11Display     : size = 128,        nnodes = 88, hash_func = g_direct_hash   (valid)
via GdkWaylandDisplay : size = 3095898016, mask = 0,    hash_func = 0x0             (not a hash table)
```

**On the close.** The reasoning was that a report from 2021 ought to have a released fix by now. The two dates are independent, though — the fix is from 2026, not 2021. And rather than argue from tag dates, here is the repository's own answer. Asking the GNOME GitLab refs API which refs contain the fix commit:

```
GET /projects/GNOME%2Fgtk/repository/commits/c3b824a8f435.../refs?type=all
  branches: ['gtk-3-24']
  tags:     []
```

Zero tags. The newest 3.24.x tag is 3.24.52 (2026-03-22); the commit was merged 2026-06-30. No GTK3 release contains it, so every distro shipping 3.24.52 still has this. Whether the original 2021 crash was this same bug I can't say — the only backtrace in the report is a bare `#0 0x0000000000000000`.

A correction to my earlier comment: I wrote that [GNOME/gtk#7749](https://gitlab.gnome.org/GNOME/gtk/-/issues/7749) is "not fixed by the commit above". That was wrong — c3b824a8 does change three atom lookups in `gtk/gtkmountoperation-x11.c`, as @m10ust pointed out. Whether it resolves every manifestation reported there I haven't verified.

For anyone rebuilding in the meantime: the upstream commit applies cleanly to the 3.24.52 tag (`git apply --check`, no fuzz), and after applying, both touched files match the current `gtk-3-24` branch.

Nothing here is actionable in this repo — the defect and the fix both live in GTK3. Reopening would only make sense as a way to track this until 3.24.53 ships.
