### ISSUE TITLE
passing NULL in for addresses in xdp_portal_compose_email crashes xdg-desktop-portal-gtk

### ISSUE THREAD

**Issue by phako** [flatpak/xdg-desktop-portal-gtk#403]
Either the documentation of xdp_portal_compose is wrong or the portal needs to handle that correctly:

```
#0  0x0000562d05998a91 in compose_mail_mailto (error=0x0, attachments=0x7ff8b00b6b30, body=<optimized out>, subject=<optimized out>, bcc=0x0, cc=0x0, addrs=0x0, info=0x562d063161b0) at src/email.c:50
#1  compose_mail (error=0x0, attachments=0x7ff8b00b6b30, body=<optimized out>, subject=<optimized out>, bcc=0x0, cc=0x0, addrs=0x0) at src/email.c:116
#2  handle_compose_email (object=<optimized out>, invocation=0x562d063056b0, arg_handle=<optimized out>, arg_app_id=<optimized out>, arg_parent_window=<optimized out>, arg_options=<optimized out>) at src/email.c:174
#3  0x00007ff8cc111746 in ffi_call_unix64 () at ../src/x86/unix64.S:105
#4  0x00007ff8cc10e4d2 in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:672
#5  0x00007ff8cd86afd3 in g_cclosure_marshal_generic
    (closure=<optimized out>, return_gvalue=<optimized out>, n_param_values=<optimized out>, param_values=<optimized out>, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ../gobject/gclosure.c:1534
#6  0x00007ff8cd864db0 in g_closure_invoke (closure=0x562d06001ea0, return_value=0x7ffc93ff4290, n_param_values=6, param_values=0x562d0602ef60, invocation_hint=0x7ffc93ff4270) at ../gobject/gclosure.c:830
#7  0x00007ff8cd8914d6 in signal_emit_unlocked_R.isra.0 (node=<optimized out>, detail=0, instance=0x562d06281a20, emission_return=0x7ffc93ff4320, instance_and_params=0x562d0602ef60) at ../gobject/gsignal.c:3743
#8  0x0000562d059a1a0b in _xdp_impl_email_skeleton_handle_method_call
    (connection=<optimized out>, sender=<optimized out>, object_path=<optimized out>, interface_name=0x7ff8b00b6080 "org.freedesktop.impl.portal.Email", method_name=0x7ff8b00b45e0 "ComposeEmail", parameters=<optimized out>, invocation=0x562d063056b0, user_data=0x562d06281a20) at src/xdg-desktop-portal-dbus.c:4223
#9  0x00007ff8ccf496ad in g_dbus_interface_method_dispatch_helper (interface=<optimized out>, method_call_func=0x562d059a1840 <_xdp_impl_email_skeleton_handle_method_call>, invocation=0x562d063056b0)
    at ../gio/gdbusinterfaceskeleton.c:613
#10 0x00007ff8ccf36969 in call_in_idle_cb (user_data=user_data@entry=0x562d063056b0) at ../gio/gdbusconnection.c:4994
#11 0x00007ff8ccd3a4cb in g_idle_dispatch (source=0x7ff8b00b68a0, callback=0x7ff8ccf36810 <call_in_idle_cb>, user_data=0x562d063056b0) at ../glib/gmain.c:5935
#12 0x00007ff8ccd3dfaf in g_main_dispatch (context=0x562d0600e980) at ../glib/gmain.c:3417
#13 g_main_context_dispatch (context=0x562d0600e980) at ../glib/gmain.c:4135
#14 0x00007ff8ccd932c8 in g_main_context_iterate.constprop.0 (context=0x562d0600e980, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4211
#15 0x00007ff8ccd3d6cf in g_main_loop_run (loop=0x562d060c54c0) at ../glib/gmain.c:4411
#16 0x0000562d05990d86 in main (argc=<optimized out>, argv=<optimized out>) at src/xdg-desktop-portal-gtk.c:326

**Comment by phako** [comment]
Ah sorrz, this was fixed already #343
